config/routes.rb
Rails.application.routes.draw do

  get '/' => 'site#index'

  resources :contacts do
    end

end

app/models/contact.rb
class Contact < ActiveRecord::Base

	validates :name, presence: true, uniqueness: true
	validates :email, presence: true, uniqueness: true
	validates :phone, presence: true

	def next
		next_contact = Contact.where("id > ?", self.id).limit(1).first
		if next_contact == nil
			Contact.first.id
		else 
			next_contact.id
		end
	end

	def previous
		previous_contact = Contact.where("id < ?", self.id).reverse_order.limit(1).first
		if previous_contact == nil
			Contact.last.id
		else 
			previous_contact.id
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def index
		@contacts = Contact.order(name: :asc)
	end
	
	def show
		begin
			@contact = Contact.find params[:id]
		rescue ActiveRecord::RecordNotFound
			# @contact = Contact.find params[:id]
			render 'no_contact_found'
		end
	end

	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new contact_params
		if @contact.save
			redirect_to '/'
		else 
			render 'new'
		end
	end

	def edit
		@contact = Contact.find params[:id]
		render 'new'
	end

	def update
		@contact = Contact.find params[:id]
		@contact.update_attributes contact_params
		if @contact.save
			redirect_to action: 'show'
		else 
			render 'new'
		end
	end

	def destroy
		@contact = Contact.find params[:id]
		@contact.destroy
		redirect_to contacts_path
	end

	private 
	def contact_params
		params.require(:contact).permit(:name, :email, :phone, :address, :notes)
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

	def index
		@contacts = Contact.order(name: :asc)
		@results = Contact.where(name: params[:query])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/contacts/index.html.erb
<div class="all_contacts">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			
			<h1>Everyone I know</h1>

			<ul><% @contacts.each do |contact| %>
				<li><%= link_to(contact.name, contact_path(contact.id))%> <%= contact.email%></li>
				<% end %>
			</ul>
	
		</div>
	</div>
</div>

app/views/contacts/new.html.erb
<div class="container">
	<div class="new_form">

		<% if @contact.errors.any? %>
			<ul>
				<% @contact.errors.full_messages.each do |message| %>
				<li><%=message%></li>
				<%end%>
			</ul>
		<%end%>

		<%= form_for [@contact] do |f| %>

			<%= f.label :name %>
			<%= f.text_field :name %><br>

			<%= f.label :email %>
			<%= f.text_field :email %><br>

			<%= f.label :phone %>
			<%= f.text_field :phone %><br>

			<%= f.label :address %>
			<%= f.text_field :address %><br>

			<%= f.label :notes %>
			<%= f.text_field :notes %><br>

			<%= f.submit 'Save' %>
		<%end%>
	</div>
</div>

app/views/contacts/no_contact_found.html.erb
<div class="container">
	<div class="centered">
		<h2>Sorry, there's nobody here. </h2><br>
		<h3><a href="/">Start over</a><h3>
	</div>
</div>

app/views/contacts/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-5 col-md-offset-3">
		
	
	
			<h1 id="contact_name"><%= @contact.name%></h1>

			<br>

			<ul class="list-unstyled contact_info">
				<li><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <%= @contact.email%></li>
				<% if @contact.phone.present? %>
					<li><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> <%= @contact.phone%></li>
				<%end%>
				<% if @contact.address.present? %>
					<li><span class="glyphicon glyphicon-home" aria-hidden="true"></span> <%= @contact.address%></li>
				<% end %>
				<% if @contact.notes.present? %>
					<li><span class="glyphicon glyphicon-flag" aria-hidden="true"></span> <%= @contact.notes%></li>
				<% end %>
				
			</ul>


		</div>
	</div>

	<div class="row">
		<div class="col-md-5 col-md-offset-3">
			<div class="contact__options">
				<%= link_to("Edit", edit_contact_path(@contact), class: "link")%>

				<%= link_to("Delete", contact_path(@contact), class: "link", method: 'delete', data: {confirm: "Are you sure?"})%>
				<a href="/" class="link">Start over</a>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-5 col-md-offset-3">
			<div class="contact__nagivation">
				<div class="previous">
					<span class="glyphicon glyphicon-triangle-left" aria-hidden="true"></span>
					<%= link_to("Previous", contact_path(@contact.previous), class: "link", id: "previous")%>
				</div>

				<div class="next">
					<%= link_to("Next", contact_path(@contact.next), class: "link", id: "next")%>
					<span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span>
				</div>

			</div>
		</div>
	</div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rolodex</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Gloria+Hallelujah' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/site/_search.html.erb
<%= form_tag( action: 'search', method: 'get') do |f| %>

	<%= label_tag :query, "Search" %>
	<%= text_field_tag :query %>

	<%= submit_tag "Search" %>
	
<%end%>

app/views/site/index.html.erb
<div class="container">
	<div class="col-md-5 col-md-offset-3">
		<div class="row">

			<h1>My Address Book</h1>

		</div>

		<div class="row">
			<div class="search">
				<%= form_tag( '/', method: 'get') do |f| %>

					<%= text_field_tag :query %>
					<%= submit_tag "Search", id: "search" %>
					
				<%end%>
			</div>	
		</div>

		<div class="row">
			<ul class="list-unstyled"><% @results.each do |result| %>
				<li><span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span><%= link_to(result.name, contact_path(result.id))%> </li>
				<% end %>
			</ul>
		</div>

		<div class="row">
			<%= link_to("See everyone", contacts_path, class: "link") %>
			<%= link_to("Add new contact", new_contact_path, class: "link") %>
		</div>

		</div>
	</div>
</div>

app/views/site/search.html.erb
<%= form_for [@search] do |f| %>

	<%= f.label :query %>
	<%= f.text_field :query %>

	<%= f.submit 'Save' %>
<%end%>